apiVersion: v1
kind: Service

metadata:
  name: authservice
  namespace: microservices

spec:
  selector:
    app: authservice

  ports:
    - protocol: TCP
      port: 7092
      targetPort: 7092

  type: ClusterIP