version: '3.8'

services:


  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


  apigateway:
    container_name: apigateway
    build:
      context: ../src/ApiGateway
      dockerfile: ApiGateway.Api/Dockerfile

    ports:
      - "7058:7058"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:7058

    restart: unless-stopped


  authservice:
    container_name: authservice
    build:
      context: ../src/AuthService
      dockerfile: AuthService.Api/Dockerfile

    ports:
      - "7092:7092"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:7092
      Kafka__BootstrapServers: kafka:9092

    restart: unless-stopped

    depends_on:
      - kafka


volumes:
  kafka_data: