version: '3.8'

services:
  authservice:
    build: ../src/AuthService/AuthService.Api
    ports:
      - "5001:80"

  userservice:
    build: ../src/UserService/UserService.Api
    ports:
      - "5002:80"

  orderservice:
    build: ../src/OrderService/OrderService.Api
    ports:
      - "5003:80"